package dev.aspyro.toomanyresources.datagen.loot;

import dev.aspyro.toomanyresources.block.ModBlocks;
import dev.aspyro.toomanyresources.item.ModItems;
import net.minecraft.data.loot.BlockLoot;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer;
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;
import net.minecraftforge.registries.RegistryObject;

public class ModBlockLootTables extends BlockLoot {

    @Override
    protected void addTables() {

        this.dropSelf(ModBlocks.BAMIRITE_BLOCK.get());
        this.dropSelf(ModBlocks.BLUE_DRAGCITE_BLOCK.get());
        this.dropSelf(ModBlocks.EISSELTE_BLOCK.get());
        this.dropSelf(ModBlocks.HELMINIUM_BLOCK.get());
        this.dropSelf(ModBlocks.JEPERCKSTONE_BLOCK.get());
        this.dropSelf(ModBlocks.KHELSTONE_BLOCK.get());
        this.dropSelf(ModBlocks.KIRIONITE_BLOCK.get());
        this.dropSelf(ModBlocks.MANXIUM_BLOCK.get());
        this.dropSelf(ModBlocks.OHLY_BLOCK.get());
        this.dropSelf(ModBlocks.RAGOUTON_BLOCK.get());
        this.dropSelf(ModBlocks.SLITHESE_BLOCK.get());
        this.dropSelf(ModBlocks.TARMENIS_BLOCK.get());
        this.dropSelf(ModBlocks.VIGNASS_BLOCK.get());
        this.dropSelf(ModBlocks.VOLUCIERA_BLOCK.get());
        this.dropSelf(ModBlocks.YGGS_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_BAMIRITE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_BLUE_DRAGCITE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_EISSELTE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_HELMINIUM_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_JEPERCKSTONE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_KHELSTONE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_KIRIONITE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_MANXIUM_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_OHLY_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_RAGOUTON_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_SLITHESE_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_TARMENIS_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_VIGNASS_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_VOLUCIERA_BLOCK.get());
        this.dropSelf(ModBlocks.RAW_YGGS_BLOCK.get());

        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_BAMIRITE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BAMIRITE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_BLUE_DRAGCITE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_BLUE_DRAGCITE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_EISSELTE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_EISSELTE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_HELMINIUM_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_HELMINIUM_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_JEPERCKSTONE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_JEPERCKSTONE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_KHELSTONE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KHELSTONE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_KIRIONITE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_KIRIONITE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_MANXIUM_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_MANXIUM_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_OHLY_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_OHLY_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAGOUTON_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_RAGOUTON_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_SLITHESE_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_SLITHESE_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_TARMENIS_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_TARMENIS_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_VIGNASS_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VIGNASS_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_VOLUCIERA_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_VOLUCIERA_BLOCK_9.get());

        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_YGGS_BLOCK_9.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_1.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_2.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_3.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_4.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_5.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_6.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_7.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_8.get());
        this.dropSelf(ModBlocks.COMPRESSED_RAW_YGGS_BLOCK_9.get());

        this.add(ModBlocks.BAMIRITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.DEEPSLATE_BAMIRITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.NETHERRACK_BAMIRITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.ENDSTONE_BAMIRITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.BLUE_DRAGCITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.DEEPSLATE_BLUE_DRAGCITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.NETHERRACK_BLUE_DRAGCITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.ENDSTONE_BLUE_DRAGCITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.EISSELTE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.DEEPSLATE_EISSELTE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.NETHERRACK_EISSELTE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.ENDSTONE_EISSELTE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.HELMINIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.DEEPSLATE_HELMINIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.NETHERRACK_HELMINIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.ENDSTONE_HELMINIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.JEPERCKSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.DEEPSLATE_JEPERCKSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.NETHERRACK_JEPERCKSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.ENDSTONE_JEPERCKSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.KHELSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.DEEPSLATE_KHELSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.NETHERRACK_KHELSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.ENDSTONE_KHELSTONE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.KIRIONITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.DEEPSLATE_KIRIONITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.NETHERRACK_KIRIONITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.ENDSTONE_KIRIONITE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.MANXIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.DEEPSLATE_MANXIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.NETHERRACK_MANXIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.ENDSTONE_MANXIUM_ORE.get(), block -> createOreDrop(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.OHLY_ORE.get(), block -> createOreDrop(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.DEEPSLATE_OHLY_ORE.get(), block -> createOreDrop(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.NETHERRACK_OHLY_ORE.get(), block -> createOreDrop(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.ENDSTONE_OHLY_ORE.get(), block -> createOreDrop(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.RAGOUTON_ORE.get(), block -> createOreDrop(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.DEEPSLATE_RAGOUTON_ORE.get(), block -> createOreDrop(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.NETHERRACK_RAGOUTON_ORE.get(), block -> createOreDrop(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.ENDSTONE_RAGOUTON_ORE.get(), block -> createOreDrop(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.SLITHESE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.DEEPSLATE_SLITHESE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.NETHERRACK_SLITHESE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.ENDSTONE_SLITHESE_ORE.get(), block -> createOreDrop(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.TARMENIS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.DEEPSLATE_TARMENIS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.NETHERRACK_TARMENIS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.ENDSTONE_TARMENIS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.VIGNASS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.DEEPSLATE_VIGNASS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.NETHERRACK_VIGNASS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.ENDSTONE_VIGNASS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.VOLUCIERA_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.DEEPSLATE_VOLUCIERA_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.NETHERRACK_VOLUCIERA_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.ENDSTONE_VOLUCIERA_ORE.get(), block -> createOreDrop(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.YGGS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.DEEPSLATE_YGGS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.NETHERRACK_YGGS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.ENDSTONE_YGGS_ORE.get(), block -> createOreDrop(block, ModItems.RAW_YGGS.get()));

        this.add(ModBlocks.POOR_BAMIRITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BAMIRITE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_BAMIRITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BAMIRITE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_BAMIRITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BAMIRITE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_BAMIRITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BAMIRITE_PIECE.get()));
        this.add(ModBlocks.POOR_BLUE_DRAGCITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BLUE_DRAGCITE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_BLUE_DRAGCITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BLUE_DRAGCITE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_BLUE_DRAGCITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BLUE_DRAGCITE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_BLUE_DRAGCITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_BLUE_DRAGCITE_PIECE.get()));
        this.add(ModBlocks.POOR_EISSELTE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_EISSELTE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_EISSELTE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_EISSELTE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_EISSELTE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_EISSELTE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_EISSELTE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_EISSELTE_PIECE.get()));
        this.add(ModBlocks.POOR_HELMINIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_HELMINIUM_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_HELMINIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_HELMINIUM_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_HELMINIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_HELMINIUM_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_HELMINIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_HELMINIUM_PIECE.get()));
        this.add(ModBlocks.POOR_JEPERCKSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_JEPERCKSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_JEPERCKSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_JEPERCKSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_JEPERCKSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_JEPERCKSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_JEPERCKSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_JEPERCKSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_KHELSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KHELSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_KHELSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KHELSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_KHELSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KHELSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_KHELSTONE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KHELSTONE_PIECE.get()));
        this.add(ModBlocks.POOR_KIRIONITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KIRIONITE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_KIRIONITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KIRIONITE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_KIRIONITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KIRIONITE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_KIRIONITE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_KIRIONITE_PIECE.get()));
        this.add(ModBlocks.POOR_MANXIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_MANXIUM_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_MANXIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_MANXIUM_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_MANXIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_MANXIUM_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_MANXIUM_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_MANXIUM_PIECE.get()));
        this.add(ModBlocks.POOR_OHLY_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_OHLY_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_OHLY_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_OHLY_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_OHLY_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_OHLY_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_OHLY_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_OHLY_PIECE.get()));
        this.add(ModBlocks.POOR_RAGOUTON_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_RAGOUTON_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_RAGOUTON_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_RAGOUTON_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_RAGOUTON_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_RAGOUTON_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_RAGOUTON_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_RAGOUTON_PIECE.get()));
        this.add(ModBlocks.POOR_SLITHESE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_SLITHESE_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_SLITHESE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_SLITHESE_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_SLITHESE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_SLITHESE_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_SLITHESE_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_SLITHESE_PIECE.get()));
        this.add(ModBlocks.POOR_TARMENIS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_TARMENIS_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_TARMENIS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_TARMENIS_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_TARMENIS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_TARMENIS_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_TARMENIS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_TARMENIS_PIECE.get()));
        this.add(ModBlocks.POOR_VIGNASS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VIGNASS_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_VIGNASS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VIGNASS_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_VIGNASS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VIGNASS_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_VIGNASS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VIGNASS_PIECE.get()));
        this.add(ModBlocks.POOR_VOLUCIERA_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VOLUCIERA_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_VOLUCIERA_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VOLUCIERA_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_VOLUCIERA_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VOLUCIERA_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_VOLUCIERA_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_VOLUCIERA_PIECE.get()));
        this.add(ModBlocks.POOR_YGGS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_YGGS_PIECE.get()));
        this.add(ModBlocks.POOR_DEEPSLATE_YGGS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_YGGS_PIECE.get()));
        this.add(ModBlocks.POOR_NETHERRACK_YGGS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_YGGS_PIECE.get()));
        this.add(ModBlocks.POOR_ENDSTONE_YGGS_ORE.get(), block -> createPoorOreDrops(block, ModItems.RAW_YGGS_PIECE.get()));

        this.add(ModBlocks.RICH_BAMIRITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_BAMIRITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_BAMIRITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_BAMIRITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BAMIRITE.get()));
        this.add(ModBlocks.RICH_BLUE_DRAGCITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_BLUE_DRAGCITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_BLUE_DRAGCITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_BLUE_DRAGCITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_BLUE_DRAGCITE.get()));
        this.add(ModBlocks.RICH_EISSELTE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_EISSELTE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_EISSELTE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_EISSELTE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_EISSELTE.get()));
        this.add(ModBlocks.RICH_HELMINIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_HELMINIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.RICH_NETHERRACK_HELMINIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.RICH_ENDSTONE_HELMINIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_HELMINIUM.get()));
        this.add(ModBlocks.RICH_JEPERCKSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_JEPERCKSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_JEPERCKSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_JEPERCKSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_JEPERCKSTONE.get()));
        this.add(ModBlocks.RICH_KHELSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_KHELSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_KHELSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_KHELSTONE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KHELSTONE.get()));
        this.add(ModBlocks.RICH_KIRIONITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_KIRIONITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_KIRIONITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_KIRIONITE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_KIRIONITE.get()));
        this.add(ModBlocks.RICH_MANXIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_MANXIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.RICH_NETHERRACK_MANXIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.RICH_ENDSTONE_MANXIUM_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_MANXIUM.get()));
        this.add(ModBlocks.RICH_OHLY_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_OHLY_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.RICH_NETHERRACK_OHLY_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.RICH_ENDSTONE_OHLY_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_OHLY.get()));
        this.add(ModBlocks.RICH_RAGOUTON_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_RAGOUTON_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.RICH_NETHERRACK_RAGOUTON_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.RICH_ENDSTONE_RAGOUTON_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_RAGOUTON.get()));
        this.add(ModBlocks.RICH_SLITHESE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_SLITHESE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.RICH_NETHERRACK_SLITHESE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.RICH_ENDSTONE_SLITHESE_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_SLITHESE.get()));
        this.add(ModBlocks.RICH_TARMENIS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_TARMENIS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.RICH_NETHERRACK_TARMENIS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.RICH_ENDSTONE_TARMENIS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_TARMENIS.get()));
        this.add(ModBlocks.RICH_VIGNASS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_VIGNASS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.RICH_NETHERRACK_VIGNASS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.RICH_ENDSTONE_VIGNASS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VIGNASS.get()));
        this.add(ModBlocks.RICH_VOLUCIERA_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_VOLUCIERA_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.RICH_NETHERRACK_VOLUCIERA_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.RICH_ENDSTONE_VOLUCIERA_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_VOLUCIERA.get()));
        this.add(ModBlocks.RICH_YGGS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.RICH_DEEPSLATE_YGGS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.RICH_NETHERRACK_YGGS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_YGGS.get()));
        this.add(ModBlocks.RICH_ENDSTONE_YGGS_ORE.get(), block -> createRichOreDrops(block, ModItems.RAW_YGGS.get()));
    }


    protected static LootTable.Builder createPoorOreDrops(Block block, Item item) {
        return createSilkTouchDispatchTable(block, applyExplosionDecay(block, LootItem.lootTableItem(item).apply(SetItemCountFunction.setCount(ConstantValue.exactly(3.0F))).apply(ApplyBonusCount.addOreBonusCount(Enchantments.BLOCK_FORTUNE))));
    }

    protected static LootTable.Builder createRichOreDrops(Block block, Item item) {
        return createSilkTouchDispatchTable(block, applyExplosionDecay(block, LootItem.lootTableItem(item).apply(SetItemCountFunction.setCount(ConstantValue.exactly(3.0F))).apply(ApplyBonusCount.addOreBonusCount(Enchantments.BLOCK_FORTUNE))));
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
    }
}
